version: "3.3"
services:
  blog-service:
    container_name: blog-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-blog-service
    ports:
      - 8088:8088
    networks:
      - brvt
    environment:
      SERVER_IP: ${SERVER_IP}
networks:
  brvt:
    name: brvt
    driver: bridge