version: "3.3"
services:
  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-api-gateway-service
    ports:
      - 8989:8989
    networks:
      - brvt
    environment:
      SERVER_IP: ${SERVER_IP}
networks:
  brvt:
    name: brvt
    driver: bridge