spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - Content-Type
          add-to-simple-url-handler-mapping: true
      routes:
#        - id: account-service
#          uri: lb://ACCOUNT-SERVICE
#          predicates:
#            - Path=/accounts/**
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
        - id: health-report-service
          uri: lb://HEALTHREPORT-SERVICE
          predicates:
            - Path=/health-report/**
        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/blog/**
#        - id: login-service
#          uri: lb://LOGIN-SERVICE
#          predicates:
#            - Path=/login/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.15.38.94:8761/eureka/
  instance:
    prefer-ip-address: true
   ip-address: ${SERVER_IP}

server:
  port: 8989