version: "3.3"
services:
  admin-service:
    container_name: admin-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-admin-service
    ports:
      - 8084:8084
    networks:
      - brvt
    environment:
      SERVER_IP: ${SERVER_IP}
networks:
  brvt:
    name: brvt
    driver: bridge